# Generated by Django 2.2.5 on 2019-09-09 12:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LandHolder',
            fields=[
                ('LandHolder_aadhaar', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator('^\\d{12}$')])),
                ('LandHolder_date_created', models.DateTimeField(verbose_name='Date Created')),
            ],
        ),
    ]
