# Generated by Django 2.2.6 on 2019-10-15 09:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField(verbose_name='index')),
                ('timestamp', models.DateTimeField(verbose_name='Time Created')),
                ('previous_hash', models.CharField(max_length=150, null=True, verbose_name='Previous Hash')),
                ('nonce', models.PositiveIntegerField(verbose_name='Nonce')),
                ('hash', models.CharField(max_length=150, verbose_name='Hash')),
            ],
        ),
        migrations.CreateModel(
            name='Chain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.PositiveIntegerField(verbose_name='Length')),
            ],
        ),
        migrations.CreateModel(
            name='FormZero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Created')),
            ],
        ),
        migrations.CreateModel(
            name='LandDetail',
            fields=[
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('LandHolder_aadhaar', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator('^\\d{12}$')], verbose_name='Aadhaar Number')),
                ('transaction_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Time Created')),
                ('Land_state', models.CharField(choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh ', 'Arunachal Pradesh '), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chhattisgarh', 'Chhattisgarh'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jammu and Kashmir ', 'Jammu and Kashmir '), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('West Bengal', 'West Bengal'), ('Andaman and Nicobar Islands', 'Andaman and Nicobar Islands'), ('Chandigarh', 'Chandigarh'), ('Dadra and Nagar Haveli', 'Dadra and Nagar Haveli'), ('Daman and Diu', 'Daman and Diu'), ('Lakshadweep', 'Lakshadweep'), ('National Capital Territory of Delhi', 'National Capital Territory of Delhi'), ('Puducherry', 'Puducherry')], max_length=150, verbose_name='State')),
                ('Land_district', models.CharField(help_text='Enter the District, under whose jurisdiction the Land falls under.', max_length=150, verbose_name='District')),
                ('Land_taluk', models.CharField(max_length=150, verbose_name='Taluk')),
                ('Land_village', models.CharField(max_length=150, verbose_name='Village')),
                ('Land_survey_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Survey Number')),
                ('Land_subdivision_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Subdivision Number')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.CharField(max_length=150, primary_key=True, serialize=False, verbose_name='TransactionID')),
                ('LandHolder_aadhaar', models.CharField(max_length=12, verbose_name='Aadhaar Number')),
                ('Land_state', models.CharField(max_length=150, verbose_name='State')),
                ('Land_district', models.CharField(max_length=150, verbose_name='District')),
                ('Land_taluk', models.CharField(max_length=150, verbose_name='Taluk')),
                ('Land_village', models.CharField(max_length=150, verbose_name='Village')),
                ('Land_survey_number', models.PositiveIntegerField(verbose_name='Survey Number')),
                ('Land_subdivision_number', models.PositiveIntegerField(verbose_name='Subdivision Number')),
                ('timestamp', models.DateTimeField(verbose_name='Time Created')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='main.Block')),
            ],
        ),
        migrations.CreateModel(
            name='T2B',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Block')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Transaction')),
            ],
        ),
        migrations.CreateModel(
            name='Peer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IP', models.CharField(max_length=150, null=True, verbose_name='IP')),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peers', to='main.Chain')),
            ],
        ),
        migrations.AddField(
            model_name='block',
            name='chain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chain', to='main.Chain'),
        ),
        migrations.CreateModel(
            name='B2C',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Block')),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Chain')),
            ],
        ),
    ]
