# Generated by Django 2.2.5 on 2019-09-09 14:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190909_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='land',
            name='Land_subdivision_number',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='land',
            name='Land_survey_number',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
